//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_MEMBER_WORKSHOP.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessToken
    {
        public int Id { get; set; }
        public string token { get; set; }
        public System.DateTime exprise { get; set; }
        public int memberId { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
